site_name: Creating FMU with Nim

theme:
  name: readthedocs
#  name: material
#  highlightjs: true


nav:
  - Introduction:
    - Objective: objective.md
    - Example - Dahlquist equation: dq.md
    - fmuTemplate.c: fmutemplate.md
    - fmuTemplate.h: fmutemplate_h.md



extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
- admonition
- codehilite
- pymdownx.details
- pymdownx.superfences
- pymdownx.arithmatex
- mdx_math:
    enable_dollar_delimiter: true

plugins:
- search
